export const predefinedTexts = [
    "Un cadeau est un message d'amour qui se transmet sans paroles.",
    "Chaque cadeau raconte une histoire, chaque histoire touche un cœur.",
    "Le plus beau des cadeaux, c'est l'attention qui l'accompagne.",
    "Un cadeau n'est pas un objet, c'est un sentiment matérialisé.",
    "La joie de donner dépasse toujours la joie de recevoir.",
    // Ajout des phrases du 18ème siècle
    "Ô douce amie, recevez ce modeste présent comme gage de mon infinie affection.",
    "Ma chère, ce présent n'est qu'un pâle reflet de l'amour que je vous porte.",
    "Que ce cadeau, en toute humilité, vous témoigne de mes sentiments les plus purs.",
    "Sous ce papier scintillant se cache mon cœur, destiné à vous seul(e).",
    "Recevez ce présent comme un symbole de l'admiration que vous m'inspirez.",
    "Que cette humble offrande vous rappelle la constance de mon attachement.",
    "Mon aimé(e), ce présent n'est qu'une pâle image de l'immensité de mes sentiments.",
    "Acceptez ce modeste don, preuve de mon indéfectible dévouement.",
    "Que ce présent soit le reflet de l'amour brûlant que j'éprouve pour vous.",
    "Ô lumière de ma vie, recevez ce cadeau comme un symbole de mon estime éternelle.",
    "Que cet humble présent vous rappelle la profondeur de mon amour.",
    "Recevez cette modeste offrande, témoignage de mon affection sincère.",
    "Mon trésor, ce cadeau n'est qu'une modeste preuve de mon adoration.",
    "Que cette modeste offrande soit le reflet de ma tendresse infinie.",
    "Recevez ce présent comme un gage de mon amour incommensurable.",
    "Ma chère, que ce cadeau vous témoigne de l'ardeur de mes sentiments.",
    "Que cet humble présent soit le miroir de mon âme, entièrement vouée à vous.",
    "Ô douce amie, acceptez ce modeste don comme signe de mon éternelle fidélité.",
    "Ce cadeau, ma chère, est l'expression de mon amour le plus profond.",
    "Recevez ce présent comme une humble offrande de mon cœur passionné.",
    "Que ce cadeau soit le reflet de la flamme éternelle qui brûle en moi.",
    "Mon aimé(e), recevez ce présent en signe de mon affection éternelle.",
    "Ce modeste don est un humble reflet de l'amour que je vous porte.",
    "Recevez cette offrande comme un témoignage de ma passion inaltérable.",


    "Un cadeau est un message d'amour qui se transmet sans paroles.",
    "Chaque cadeau raconte une histoire, chaque histoire touche un cœur.",
    "Le plus beau des cadeaux, c'est l'attention qui l'accompagne.",
    "Un cadeau n'est pas un objet, c'est un sentiment matérialisé.",
    "La joie de donner dépasse toujours la joie de recevoir.",
    // Ajout des phrases du 18ème siècle
    "Ô douce amie, recevez ce modeste présent comme gage de mon infinie affection.",
    "Ma chère, ce présent n'est qu'un pâle reflet de l'amour que je vous porte.",
    "Que ce cadeau, en toute humilité, vous témoigne de mes sentiments les plus purs.",
    "Sous ce papier scintillant se cache mon cœur, destiné à vous seul(e).",
    "Recevez ce présent comme un symbole de l'admiration que vous m'inspirez.",
    "Que cette humble offrande vous rappelle la constance de mon attachement.",
    "Mon aimé(e), ce présent n'est qu'une pâle image de l'immensité de mes sentiments.",
    "Acceptez ce modeste don, preuve de mon indéfectible dévouement.",
    "Que ce présent soit le reflet de l'amour brûlant que j'éprouve pour vous.",
    "Ô lumière de ma vie, recevez ce cadeau comme un symbole de mon estime éternelle.",
    "Que cet humble présent vous rappelle la profondeur de mon amour.",
    "Recevez cette modeste offrande, témoignage de mon affection sincère.",
    "Mon trésor, ce cadeau n'est qu'une modeste preuve de mon adoration.",
    "Que cette modeste offrande soit le reflet de ma tendresse infinie.",
    "Recevez ce présent comme un gage de mon amour incommensurable.",
    "Ma chère, que ce cadeau vous témoigne de l'ardeur de mes sentiments.",
    "Que cet humble présent soit le miroir de mon âme, entièrement vouée à vous.",
    "Ô douce amie, acceptez ce modeste don comme signe de mon éternelle fidélité.",
    "Ce cadeau, ma chère, est l'expression de mon amour le plus profond.",
    "Recevez ce présent comme une humble offrande de mon cœur passionné.",
    "Que ce cadeau soit le reflet de la flamme éternelle qui brûle en moi.",
    "Mon aimé(e), recevez ce présent en signe de mon affection éternelle.",
    "Ce modeste don est un humble reflet de l'amour que je vous porte.",
    "Recevez cette offrande comme un témoignage de ma passion inaltérable.",



    "Un cadeau est un message d'amour qui se transmet sans paroles.",
    "Chaque cadeau raconte une histoire, chaque histoire touche un cœur.",
    "Le plus beau des cadeaux, c'est l'attention qui l'accompagne.",
    "Un cadeau n'est pas un objet, c'est un sentiment matérialisé.",
    "La joie de donner dépasse toujours la joie de recevoir.",
    // Ajout des phrases avec des rimes
    "Pour toi, mon doux trésor, je n'ai que des mots d'or.",
    "Un cadeau bien choisi, pour toi mon seul souci.",
    "Ce présent, doux refrain, est l'écho de mon cœur plein.",
    "Pour toi, étoile des nuits, ce cadeau est infini.",
    "Mon amour, ma destinée, ce cadeau est destiné.",
    "Sous l'éclat de ce jour, je t'offre tout mon amour.",
    "Pour toi, douce lumière, ce cadeau est sincère.",
    "Un présent en harmonie, pour l'amour de ma vie.",
    "Ce cadeau est un lien, entre nos cœurs et nos mains.",
    "Pour toi, ô mon aimé, ce présent est un baiser."


];
